FROM php:7.4.33-zts-alpine
RUN apk update
RUN apk add --no-cache nodejs npm sudo
RUN npm install -g gulp

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"
RUN mv composer.phar /usr/local/bin/composer

RUN addgroup -g 1000 node
RUN adduser -u 1000 -G node -D node
RUN mkdir -p /etc/sudoers.d
RUN echo "node ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/node
RUN chmod 0440 /etc/sudoers.d/node

USER node
RUN mkdir -p /home/node/app
WORKDIR /home/node/app
ENTRYPOINT [ "tail", "-f", "/dev/null" ]