version: '3'
name: wordpress
services:
  web:
    container_name: wordpress
    image: mochrira/wordpress:latest
    volumes:
      - $PWD/public:/var/www/html
      - $PWD/projects:/home/wordpress/projects
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`wordpress.local`) || HostRegexp(`wordpress.local `, `{subdomain:[a-z]+}.wordpress.local`)"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
    networks:
      - environment
      - database

networks:
  environment:
    name: environment
    external: true
  
  database:
    name: database
    external: true