version: '3'
name: wordpress
services:
  web:
    container_name: wordpress
    image: mochrira/wordpress:latest
    build: 
      context: ./
      dockerfile: dockerfile
    volumes:
      - $HOME/wordpress:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`wordpress.local`) || HostRegexp(`wordpress.local `, `{subdomain:[a-z]+}.wordpress.local`)"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
    networks:
      - environment
      - database
    restart: unless-stopped

networks:
  environment:
    external: true

  database:
    external: true