version: '3'
name: wordpress
services:
  web:
    container_name: wordpress_container
    image: mochrira/wordpress:latest
    build: 
      context: ./
      dockerfile: dockerfile
    volumes:
      - ./private/wordpress:/var/www/html
    networks:
      - wordpress

networks:
  wordpress:
    driver: bridge
    name: wordpress